export SPLUNK_USERNAME='myamavaram@softility.com'
export SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
export STACK_USERNAME=${STACK_USERNAME}
export STACK_PASSWORD=${STACK_PASSWORD}
export STACK_TOKEN=${STACK_TOKEN}