#!/bin/bash
export SPLUNK_USERNAME=${SPLUNK_ES_USERNAME}
export SPLUNK_PASSWORD=${SPLUNK_ES_PASSWORD}
export STACK_USERNAME=${STACK_ES_USERNAME}
export STACK_PASSWORD=${STACK_ES_PASSWORD}
export STACK_TOKEN=${STACK_ES_TOKEN}

echo 'SPLUNK_USERNAME: $SPLUNK_USERNAME'
echo 'SPLUNK_PASSWORD: $SPLUNK_PASSWORD'